version: '2'
services:
  jhipsterreact-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/jhipsterReact/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipsterReact
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
